[debug] [2018-08-14T19:38:21.827Z] ----------------------------------------------------------------------
[debug] [2018-08-14T19:38:21.829Z] Command:       /usr/local/Cellar/node@8/8.11.3_1/bin/node /usr/local/bin/firebase functions:shell
[debug] [2018-08-14T19:38:21.829Z] CLI Version:   4.1.0
[debug] [2018-08-14T19:38:21.829Z] Platform:      darwin
[debug] [2018-08-14T19:38:21.829Z] Node Version:  v8.11.3
[debug] [2018-08-14T19:38:21.830Z] Time:          Tue Aug 14 2018 21:38:21 GMT+0200 (CEST)
[debug] [2018-08-14T19:38:21.830Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-08-14T19:38:21.838Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-08-14T19:38:21.838Z] > authorizing via signed-in user
[debug] [2018-08-14T19:38:21.840Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/analog-pics-a1a3b  
 
[debug] [2018-08-14T19:38:22.477Z] <<< HTTP RESPONSE 200
[debug] [2018-08-14T19:38:22.478Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/analog-pics-a1a3b/tokens  
 
[debug] [2018-08-14T19:38:23.084Z] <<< HTTP RESPONSE 200
[debug] [2018-08-14T19:38:23.702Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:113:21)
    at Command.module.exports [as _action] (/usr/local/lib/node_modules/firebase-tools/lib/functionsShellCommandAction.js:18:6)
    at /usr/local/lib/node_modules/firebase-tools/lib/command.js:202:29
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[error] 
[error] Error: An unexpected error has occurred.
